export const studentData = [
  {
    id: 1,
    studentName: "Koduru Hema Sai",
    instituteName: "Sathyabama Institute of Science and Technology",
    courseName: "Python Full Stack Development Training Program",
    courseShortName: "Python Full Stack",
    startDate: "24th February 2025",
    endDate: "28th March 2025",
    hours: 120,
    awardDate: "2nd April 2025",
  },
  {
    id: 2,
    studentName: "Koduru Hema Sai",
    instituteName: "Sathyabama Institute of Science and Technology",
    courseName: "Java Full Stack Development Training Program",
    courseShortName: "Java Full Stack",
    startDate: "24th February 2025",
    endDate: "28th March 2025",
    hours: 120,
    awardDate: "2nd April 2025",
  },
  {
    id: 3,
    studentName: "Muskan Verma",
    instituteName: "Sathyabama Institute of Science and Technology",
    courseName: "Full Stack Development Training Program",
    courseShortName: "Full Stack Dev",
    startDate: "24th February 2025",
    endDate: "28th March 2025",
    hours: 120,
    awardDate: "2nd April 2025",
  },
];
